#!/usr/bin/env python3

import os, sys, time, signal

LocalModsPath = 'components'
InstalledModsPath = f'/usr/local/share/pplockd/{LocalModsPath}'
ConfPath = '/etc/pplockd'

sys.path.append(InstalledModsPath if os.path.isdir(InstalledModsPath) else LocalModsPath)

if os.path.isdir(ConfPath):
	sys.path.append(ConfPath)

for Sig in (signal.SIGTERM, signal.SIGINT):
	signal.signal(Sig, lambda *Discarded : os._exit(0))

import PPConfig, XorgControl, KernelControl, PPButtonMon, PPActions
from PPTypes import PPLockState

class MainObj:
	Instance = None
	def __init__(self):
		self.ButtonMon = PPButtonMon.ButtonMonitor()
		self.LockState = PPLockState()
	
		type(self).Instance = self
	
	def MainLoop(self):
		print('Entering main loop')
		
		while True:
			NewState = self.ButtonMon.WaitForChange(0.1) #Wait a 10th of a second for something to happen				
			
			if NewState:
				print(f'Processing button event {NewState}')
				
				for Func in PPConfig.EventTriggerFuncs:
					if Func(NewState):
						break
				
			#Hard lock management after this point
			if not self.LockState.HardLocked or self.LockState.LastHardLockWake == 0:
				continue
				
			if self.LockState.LastHardLockWake + PPConfig.HardLockResleepSecs <= int(time.time()):
				print(f'{PPConfig.HardLockResleepSecs} secs up, sleeping again.')
				
				if KernelControl.ActivateSleep():
					self.LockState.LastHardLockWake = int(time.time())
				else:
					print('Failed to resume hard lock, falling back to soft lock.')
					
					self.LockState.HardLocked = False
					PPActions.PerformSoftLock()

def Init():
	if len(sys.argv) <= 1 or sys.argv[1] != '--nodaemon':
		PID = os.fork()
	
		if PID != 0:
			print('Daemonizing')
			sys.exit(0)
	
	MObj = MainObj()
	
	MObj.MainLoop()
	
Init()

